resources:
- name: hello
  type: git
  source:
    uri: https://github.com/superbrothers-sandbox/node-js-sample
    branch: master
- name: hello-image
  type: docker-image
  source:
    repository: superbrothers/hello
    username: superbrothers
    password: {{docker-password}}

jobs:
- name: unit-tests
  plan:
  - aggregate:
    - get: hello
      trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node}
      inputs:
      - name: hello
      run:
        path: sh
        args:
        - -exc
        - |
          cd ./hello
            npm install
            npm test
- name: build-docker-image
  plan:
  - aggregate:
    - get: hello
      trigger: true
      passed: [unit-tests]
  - put: hello-image
    params:
      build: hello
